cinema-sync/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  root 'home#index'

  get 'home/about', to: "home#about", as: 'about'

  resources :users do
    resource :room do
      resources :messages
      resource :video
    end
  end

  mount ActionCable.server => '/cable'

end

cinema-sync/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user && user.admin?
        can :access, :rails_admin
        can :dashboard
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

cinema-sync/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cinema-sync/app/models/message.rb
class Message < ApplicationRecord
  validates :body, :presence => true

  belongs_to :user
  belongs_to :room
end

cinema-sync/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  validates_presence_of :title

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :messages, dependent: :destroy
  has_one :video, dependent: :destroy
end

cinema-sync/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :email, :password, :password_confirmation, presence: true

  has_one :room, dependent: :destroy
  has_many :messages, dependent: :destroy

  def admin?
    role == 'admin'
  end
end

cinema-sync/app/models/video.rb
class Video < ApplicationRecord
  belongs_to :room

  YOUTUBE_VIDEO_REGEX = /(https?):\/\/(www.)?(youtube.com\/)(watch\?v=|embed\/)(.{8,14})/

  before_save :create_iframe_link

  validates_presence_of :title
  validates_format_of :link, with: YOUTUBE_VIDEO_REGEX

  def create_iframe_link
    video_hash = link.match(YOUTUBE_VIDEO_REGEX)[5]
    self.link = "https://www.youtube.com/embed/#{video_hash}"
  end

end

cinema-sync/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
end

cinema-sync/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.all.order(created_at: "desc")
  end

  def about

  end
end

cinema-sync/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_user_and_room

  def index
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.room = @room
    if @message.save
      ActionCable.server.broadcast 'messages',
        message: @message.body,
        user: @message.user.username,
        chatroom_id: @room.id
      head :ok
    end
  end

  private
  def set_user_and_room
    @user = User.find(params[:user_id])
    @room = @user.room
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

cinema-sync/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_user, except: [:index, :new]
  before_action :set_room, except: [:index, :new, :create]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @user.create_room(room_params)
    redirect_to user_room_path(current_user)
  end

  def show
    @video = @room.video || Video.new
    ActionCable.server.broadcast 'videos',
      time: @video.time,
      start: @video.start,
      video_id: @video.link,
      room_id: @room.id
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @video }
    # end
  end

  def update
    @room.update_attributes(room_params)
    redirect_to user_room_path
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_room
    @room = @user.room
  end

  def room_params
    params.require(:room).permit(:user_id, :title, :image)
  end
end

cinema-sync/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

cinema-sync/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
     super
  end
end

cinema-sync/app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :set_user_room
  before_action :set_video, except: [:new, :create]

  def new
    @video = Video.new
  end

  def create
    @video = Video.create(videos_params.merge(room_id: @room.id))
    redirect_to user_room_path(@user)
  end

  def update
    @video.update_attributes(videos_params)
    redirect_to user_room_path(@user)
  end

  def destroy
    @video.destroy
    redirect_to user_room_path(@user)
  end

  private

  def videos_params
    params.require(:video).permit(:title, :link, :time, :start)
  end

  def set_user_room
    @user = User.find(params[:user_id])
    @room = @user.room
  end

  def set_video
    @video = @room.video || Video.new
  end

end

cinema-sync/app/helpers/application_helper.rb
module ApplicationHelper
end

cinema-sync/app/helpers/messages_helper.rb
module MessagesHelper
end

cinema-sync/app/helpers/rooms_helper.rb
module RoomsHelper
end

cinema-sync/app/views/home/_main_content.html.erb
<div class="container main-content">
  <div class="main-content-header container">
    <h2 class="main-content-header-title">List of available rooms</h2>
  </div>
  <%= render 'rooms' %>
</div>

cinema-sync/app/views/home/_rooms.html.erb
<div class="container rooms-container">
  <% @rooms.all.each do |room| %>
    <%= render 'rooms/room', room: room %>
  <% end %>
</div>

cinema-sync/app/views/home/about.html.erb
<div class="about-container">
	<h1>CinemaSync</h1>
	<span>Service for synchronized watching videos with your friends.</span>
</div>

cinema-sync/app/views/home/index.html.erb
<%= render 'main_content' %>
<%= render 'footer' %>
<% if current_user && !current_user.room %>
<button class="button-create" data-toggle="modal" data-target="#create-room-pop-up">
  <span class="glyphicon glyphicon-plus"></span>
</button>
<% end %>

cinema-sync/app/views/layouts/_create_room_pop_up.html.erb
<% if current_user %>
<div id="create-room-pop-up" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for :room, url: user_room_path(current_user), remote: true, authenticity_token: true, class: "form-group" do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2>New Room</h2>
      </div>
      <div class="modal-body">
        <div class="wrapper-input">
          <div class="wrapper-input-field-short">
            <strong>
              Room name:
            </strong>
          </div>
          <div class="wrapper-input-field-long">
            <%= f.text_field :title, placeholder: "Name...", class: "form-control"%>
          </div>
        </div>
        <div class="wrapper-input-field-short">
          <strong>
            Room picture:
          </strong>
        </div>
        <div class="wrapper-input-field-short">

          <label class="btn btn-default btn-file">
            Browse
            <%= f.file_field :image, class: "picture-room form-control", style: "display: none" %>
            <input type="file" style="display: none;">
          </label>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Create", class: "btn btn-primary" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

cinema-sync/app/views/layouts/_header.html.erb
<div class="header">
  <div class="logo pull-left">
    <h2 class="logo-text">
      <a href="<%= root_path %>">CinemaSync</a>
    </h2>
  </div>

  <div class="site-navigation pull-right">
    <ul class="site-navigation-list">
      <li class="site-navigation-list-item">
        <a href="<%= root_path %>" class="site-navigation-text">Home</a>
      </li>
      <li class="site-navigation-list-item">
        <a href="<%= about_path %>" class="site-navigation-text">About</a>
      </li>
      <% if !user_signed_in? %>
      <li class="site-navigation-list-item">
        <%= link_to "Sign in", new_user_session_path, class: "site-navigation-text"%>
      </li>
    <% else %>
      <li class="site-navigation-list-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "site-navigation-text" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render 'layouts/create_room_pop_up' %>

cinema-sync/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaSync</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

cinema-sync/app/views/messages/_message.html.erb
	<div class="chat-box">
		<div class="user-box">
			<%= image_tag 'user.png', class: 'user-img' %>
			<p class="username-field"><%= message.user.username %></p>
		</div>
		<div class="message-box">
			<p class="message-field"><%= message.body %></p>
		</div>
	</div>

cinema-sync/app/views/rooms/_add_video_pop_up.html.erb
<% if current_user %>
<div id="add-video-pop-up" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for @video, url: user_room_video_path(current_user), class: "add-video-form" do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2>Add video</h2>
      </div>
      <div class="modal-body">
        <div class="wrapper-input">
          <div class="wrapper-input-field-short">
            <%= f.label "Name" %>
          </div>
          <div class="wrapper-input-field-long">
            <%= f.text_field :title, class: "form-control", required: true %>
          </div>
        </div>
        <div class="wrapper-input-field-short ">
          <%= f.label "Link" %>
        </div>
        <div class="wrapper-input-field-long">
          <%= f.text_field :link, class: "form-control", pattern: "(https?):\/\/(www.)?(youtube.com\/)(watch\?v=|embed\/)(.{8,14})", placeholder: "https://www.youtube.com/watch?v=abcdefghjkl", required: true %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" id="add-video-button">Save</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

cinema-sync/app/views/rooms/_chat.html.erb
<div class="col-md-4">
  <div class="room-page-body-chat">
    <div class="room-page-body-chat-header">
      Chat
    </div>
    <div class="room-page-body-chat-body">
      <ul class="chat" data-chatroom="<%= @room.id %>">
        <%= render @room.messages.all %>
      </ul>
      <% if current_user %>
      <div class="panel-footer" data-message-room="<%= @room.id %>">
        <%= form_for [@user, @room, @room.messages.build], remote: true do |f| %>
        <div class="input-group">
          <%= f.text_field :body, class: "form-control message-content" %>
          <span class="input-group-btn">
            <%= f.submit "Send", class: "btn btn-default" %>
          </span>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>
</div>

cinema-sync/app/views/rooms/_room.html.erb
<div class="col-md-4 rooms-container-item">
  <div class="rooms-container-item-body">
    <a href="<%= user_room_path(room.user_id) %>">
      <div class="img-preview">
        <% if room.image.present? %>
          <%= image_tag room.image.url, class: 'img-responsive' %>
        <% else %>
          <%= image_tag 'default-item.png', class: 'img-responsive' %>
        <% end %>
        <div class="triangle-preview"></div>
      </div>
    </a>
    <div class="rooms-container-item-body-title">
      <h2>
        <a href="<%= user_room_path(room.user_id) %>"><%= room.title %></a>
      </h2>
    </div>
  </div>
</div>

cinema-sync/app/views/rooms/create.js.erb
$('.rooms-container').prepend("<%= escape_javascript render @room %>")

$("#create-room-pop-up").find('input').each(function(i, el) {
  $(el).val('');
});
$("#create-room-pop-up").modal('toggle');

popupMessage('success', 'Room is created');

cinema-sync/app/views/rooms/edit.html.erb
<div class="container">

  <div class="form-group col-md-6 col-sm-12 col-md-offset-3 edit-room">
    <%= form_for @room, url: { action: :update }, method: :put do |f| %>
    <p>
      <%= f.label "Room name:", class: "edit-room-label" %>
      <%= f.text_field :title, class: 'form-control' %>
    </p>

    <% if @room.video %>
    <p>
      <%= f.label "Video title:", class: "edit-room-label"  %>
      <%= f.text_field :video_title, class: 'form-control' %>
    </p>

    <p>
      <%= f.label "Video url:", class: "edit-room-label"  %>
      <%= f.text_field :video_url, class: 'form-control',required: true, value: "", pattern: "(https?)://(www.)?youtube.com/watch[?]v=(.{8,14})" %>
    </p>
    <% end %>

    <%= f.submit class: 'btn btn-success edit-room-form-button' %>
    <% end %>
  </div>

</div>

cinema-sync/app/views/rooms/new.html.erb
<div class="form-group">
  <%= form_for @room, url: {:action => :create} do |f| %>
      <p>
        <%= f.label "Title" %>
        <%= f.text_field :title, class: 'form-control' %>
      </p>

      <p>
        <%= f.label "Youtube URL" %>
        <%= f.text_field :video_url, class: 'form-control' %>
      </p>

      <div class="btn-group" role="group">
        <%= f.submit class: 'btn btn-success', id: "submit" %>
      </div>
  <% end %>
</div>

cinema-sync/app/views/rooms/show.html.erb
<div class="container-fluid room-page">
  <div class="room-page-header" controller="<%= user_room_path(current_user) if current_user && @room.user.id == current_user.id %>">
    <h2>
      <%= @room.title %>
    </h2>
    <% if current_user && @room.user.id == current_user.id  %>
    <span class="glyphicon glyphicon-pencil edit-sign"></span>
    <% end %>
  </div>
  <div class="room-page-body">
    <div class="col-md-8">
      <div class="room-page-body-video-block">
        <div class="room-page-body-video-block-header">
          <%= @room.video.title if @room.video  %>
        </div>
        <div class="room-page-body-video-block-video">
          <% if @room.video %>
          <div id="player"></div>


          <div id="video-room-<%=@room.id%>" controller="<%=user_room_video_path(current_user) if current_user%>" isOwner="<%= current_user ? @room.user.id == current_user.id : false %>">

          </div>
        <% else %>
          <% if @room.user == current_user %>
          <div class="add-video-area">
            <div class="add-video-area-target" id="add-video-to-room" data-toggle="modal" data-target="#add-video-pop-up">
              <span class="glyphicon glyphicon-plus"></span>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>

      <div class="room-page-body-options">
        <% if @room.user == current_user %>
        <div class="admin-options">
          <% if @room.video %>
          <div data-toggle="modal" data-target="#add-video-pop-up" class="edit-room-button option-button">
            <h2>Change video</h2>
          </div>
          <% end %>
          <a class="delete-room-button option-button" rel="nofollow" data-method="delete" href="<%= user_room_path(current_user) %>">
            <h2>
              Delete room
            </h2>
          </a>

        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="room-page-body-chat">
        <div class="room-page-body-chat-header">
            Chat
         </div>
        <div class="room-page-body-chat-body">
          <ul id="chat">
            <%= render @room.messages.all %>
          </ul>
          <% if user_signed_in? %>
          <div class="panel-footer">
            <%= form_for [@user, @room, @room.messages.build], remote: true do |f| %>
                <div class="input-group">
                  <%= f.text_field :body, class: "form-control" %>
                  <span class="input-group-btn">
                        <%= f.submit "Send", class: "btn btn-default" %>
                      </span>
                </div>
            <% end %>
          </div>
          <% end %>
        </div>

    </div>

    <%= render 'chat' %>

  </div>
</div>

<%= render 'add_video_pop_up' %>

cinema-sync/app/views/rooms/update.js.erb
window.location.reload()

cinema-sync/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>